#!/usr/bin/env python3
"""Evidence builder for the TSP demonstrator.

The demonstrator intentionally consumes only SUMO/TraCI artifacts generated by
the project runs: tripinfo XML/KPI JSON, TSP decision logs, TSP actuation logs,
and C-ITS/TSP summaries. It does not fabricate operational observations.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from pps57_sumo.parse_tripinfo import parse_tripinfo


JsonDict = Dict[str, Any]


@dataclass(frozen=True)
class DemonstratorRun:
    label: str
    root: Path
    summary: JsonDict
    cits_summary: JsonDict
    decisions: List[JsonDict]
    actuations: List[JsonDict]
    kpis: Optional[JsonDict]


def load_demonstrator_run(root: str | Path, label: str) -> DemonstratorRun:
    run_root = Path(root)
    if label == "sumo_baseline":
        return DemonstratorRun(
            label=label,
            root=run_root,
            summary={},
            cits_summary={},
            decisions=[],
            actuations=[],
            kpis=_load_kpis(run_root, label),
        )
    summary = _read_json(run_root / "reports/tsp_emulation_summary.json") or {}
    cits_summary = _read_json(run_root / "reports/cits_emulation_summary.json") or {}
    decisions = _read_jsonl(run_root / "outputs/tsp_decisions.jsonl")
    actuations = _read_jsonl(run_root / "outputs/tsp_actuation.jsonl")
    kpis = _load_kpis(run_root, label)
    return DemonstratorRun(
        label=label,
        root=run_root,
        summary=summary,
        cits_summary=cits_summary,
        decisions=decisions,
        actuations=actuations,
        kpis=kpis,
    )


def build_demonstrator_report(
    *,
    baseline: DemonstratorRun,
    tsp: DemonstratorRun,
    tsp_controller: DemonstratorRun,
    policy_optimization_summary: Optional[JsonDict] = None,
) -> JsonDict:
    runs = {
        baseline.label: _run_payload(baseline),
        tsp.label: _run_payload(tsp),
        tsp_controller.label: _run_payload(tsp_controller),
    }
    comparisons = {
        "tsp_vs_sumo_baseline_kpis": _kpi_delta(baseline.kpis, tsp.kpis),
        "tsp_controller_vs_sumo_baseline_kpis": _kpi_delta(baseline.kpis, tsp_controller.kpis),
        "tsp_controller_vs_tsp_runtime": _runtime_delta(tsp, tsp_controller),
    }
    return {
        "report_type": "tsp_control_demonstrator",
        "data_policy": {
            "operational_data_source": "SUMO/TraCI run artifacts",
            "synthetic_operational_data": False,
        },
        "runs": runs,
        "comparisons": comparisons,
        "offline_policy_counterfactuals": _offline_counterfactuals(
            runs.get(tsp.label, {}), policy_optimization_summary
        ),
        "verdict": _verdict(comparisons),
        "evidence_paths": {
            baseline.label: _evidence_paths(baseline),
            tsp.label: _evidence_paths(tsp),
            tsp_controller.label: _evidence_paths(tsp_controller),
        },
        "limitations": _limitations(baseline, tsp, tsp_controller),
    }


def write_demonstrator_report(
    report: JsonDict,
    *,
    json_path: str | Path,
    markdown_path: str | Path,
) -> None:
    json_output = Path(json_path)
    markdown_output = Path(markdown_path)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    markdown_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.write_text(json.dumps(report, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")
    markdown_output.write_text(render_demonstrator_markdown(report), encoding="utf-8")


def render_demonstrator_markdown(report: JsonDict) -> str:
    lines = [
        "# TSP Demonstrator Report",
        "",
        "## Scope",
        "",
        "- Data source: SUMO/TraCI artifacts generated by project runs.",
        "- Synthetic operational data: false.",
        f"- Verdict: {report.get('verdict', {}).get('status', 'unknown')}.",
        f"- Reason: {report.get('verdict', {}).get('reason', '')}.",
        "",
        "## Runtime Evidence",
        "",
        "| Run | Decisions | Applied | Safety blocks | Controller rejects | Actuation enabled |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for label, payload in report.get("runs", {}).items():
        runtime = payload.get("runtime", {})
        lines.append(
            "| {label} | {decisions} | {applied} | {blocks} | {rejects} | {enabled} |".format(
                label=_escape(label),
                decisions=runtime.get("total_decisions", 0),
                applied=runtime.get("applied_events", 0),
                blocks=runtime.get("blocked_by_safety", 0),
                rejects=runtime.get("controller_rejections", 0),
                enabled=_escape(_fmt(runtime.get("actuation_enabled")) or "n/a"),
            )
        )

    lines.extend(["", "## SUMO KPIs", ""])
    for name, comparison in report.get("comparisons", {}).items():
        if not name.endswith("_kpis"):
            continue
        lines.extend([f"### {_escape(name)}", ""])
        if not comparison.get("available"):
            lines.extend(["KPI comparison unavailable: missing tripinfo/KPI artifacts.", ""])
            continue
        lines.extend(
            [
                "| Group | Metric | Baseline | Candidate | Delta |",
                "|---|---|---:|---:|---:|",
            ]
        )
        for row in comparison.get("rows", []):
            lines.append(
                "| {group} | {metric} | {baseline} | {candidate} | {delta} |".format(
                    group=_escape(str(row.get("group", ""))),
                    metric=_escape(str(row.get("metric", ""))),
                    baseline=_fmt(row.get("baseline")),
                    candidate=_fmt(row.get("candidate")),
                    delta=_fmt(row.get("delta")),
                )
            )
        lines.append("")

    lines.extend(["## Controller And Safety Reasons", ""])
    controller_run = report.get("runs", {}).get("tsp_controller", {})
    runtime = controller_run.get("runtime", {})
    lines.extend(_counter_section("Safety blocks", runtime.get("safety_block_by_reason", {})))
    lines.extend(_counter_section("Controller rejects", runtime.get("controller_rejection_by_reason", {})))

    counterfactuals = report.get("offline_policy_counterfactuals", {})
    lines.extend(["", "## Offline Policy Counterfactuals", ""])
    if not counterfactuals.get("available"):
        note = counterfactuals.get("note") or "no optimizer summary joined."
        lines.extend([f"Offline counterfactuals unavailable: {_escape(str(note))}", ""])
    else:
        lines.append(f"- {_escape(str(counterfactuals.get('note', '')))}")
        lines.append(
            f"- Offline scenarios: {counterfactuals.get('scenario_count', 0)}; "
            f"action changes vs baseline: {counterfactuals.get('offline_action_changes_vs_baseline', 0)}, "
            f"unchanged: {counterfactuals.get('offline_action_unchanged_vs_baseline', 0)}."
        )
        lines.append("")
        lines.extend(_counter_section("Runtime by action", counterfactuals.get("runtime_by_action", {})))
        lines.extend(_counter_section("Offline baseline by action", counterfactuals.get("offline_baseline_by_action", {})))
        lines.extend(_counter_section("Offline selected by action", counterfactuals.get("offline_selected_by_action", {})))

    limitations = report.get("limitations", [])
    if limitations:
        lines.extend(["", "## Limitations", ""])
        lines.extend([f"- {_escape(str(item))}" for item in limitations])
    lines.append("")
    return "\n".join(lines)


def _offline_counterfactuals(tsp_payload: JsonDict, policy_summary: Optional[JsonDict]) -> JsonDict:
    """Join the runtime action mix against the offline optimizer counterfactuals.

    Reuses the EXISTING optimizer summary (baseline/selected by_action +
    action-change counts) so the report surfaces 'action taken vs alternatives
    considered' without recomputing the reward function inside the live loop.
    """
    if not policy_summary:
        return {"available": False, "note": "No policy_optimization_summary provided."}
    runtime = tsp_payload.get("runtime", {}) if isinstance(tsp_payload, dict) else {}
    return {
        "available": True,
        "methodology": policy_summary.get("methodology"),
        "scenario_count": policy_summary.get("scenario_count"),
        "offline_baseline_by_action": policy_summary.get("baseline_by_action", {}),
        "offline_selected_by_action": policy_summary.get("selected_by_action", {}),
        "offline_action_changes_vs_baseline": policy_summary.get("optimized_action_changes_vs_baseline"),
        "offline_action_unchanged_vs_baseline": policy_summary.get("optimized_action_unchanged_vs_baseline"),
        "runtime_by_action": runtime.get("by_action", {}),
        "note": (
            "Offline argmax-over-safe-candidates counterfactuals from the optimizer summary; "
            "reward is NOT recomputed in the live decision loop."
        ),
    }


def _run_payload(run: DemonstratorRun) -> JsonDict:
    controller_rejections = _controller_rejections(run.actuations)
    runtime = {
        "root": str(run.root),
        "total_decisions": _summary_or_count(run.summary, "total_decisions", run.decisions),
        "applied_events": _summary_or_count(run.summary, "applied_events", [a for a in run.actuations if a.get("applied")]),
        "blocked_by_safety": _summary_or_count(
            run.summary,
            "blocked_by_safety",
            [d for d in run.decisions if d.get("status") == "blocked_by_safety"],
        ),
        "controller_rejections": len(controller_rejections),
        "actuation_enabled": run.summary.get("actuation_enabled"),
        "by_action": run.summary.get("by_action") or _count_by(run.decisions, "action"),
        "by_status": run.summary.get("by_status") or _count_by(run.decisions, "status"),
        "safety_block_by_reason": _count_by(
            [d for d in run.decisions if d.get("status") == "blocked_by_safety"],
            "reason",
        ),
        "controller_rejection_by_reason": dict(Counter(_controller_rejection_reason(item) for item in controller_rejections)),
        "per_tls": _per_tls(run.decisions, run.actuations, controller_rejections),
        "green_time": _green_time(run.decisions),
        "score_attribution": _score_attribution(run.decisions),
    }
    return {
        "runtime": runtime,
        "kpis": run.kpis,
        "summary": run.summary,
        "cits_summary": run.cits_summary,
    }


def _kpi_delta(baseline: Optional[JsonDict], candidate: Optional[JsonDict]) -> JsonDict:
    if not baseline or not candidate:
        return {"available": False, "rows": []}
    rows = []
    for group in ["all_vehicles", "buses", "general_traffic"]:
        baseline_group = baseline.get(group, {})
        candidate_group = candidate.get(group, {})
        for metric in [
            "vehicles",
            "mean_duration_s",
            "mean_waiting_time_s",
            "mean_time_loss_s",
            "mean_depart_delay_s",
        ]:
            base_value = baseline_group.get(metric)
            cand_value = candidate_group.get(metric)
            rows.append(
                {
                    "group": group,
                    "metric": metric,
                    "baseline": base_value,
                    "candidate": cand_value,
                    "delta": _delta(base_value, cand_value),
                }
            )
    return {"available": True, "rows": rows}


def _runtime_delta(tsp: DemonstratorRun, controller: DemonstratorRun) -> JsonDict:
    tsp_payload = _run_payload(tsp)["runtime"]
    controller_payload = _run_payload(controller)["runtime"]
    keys = ["total_decisions", "applied_events", "blocked_by_safety", "controller_rejections"]
    return {
        "available": True,
        "rows": [
            {
                "metric": key,
                "tsp": tsp_payload.get(key),
                "tsp_controller": controller_payload.get(key),
                "delta": _delta(tsp_payload.get(key), controller_payload.get(key)),
            }
            for key in keys
        ],
    }


def _verdict(comparisons: JsonDict) -> JsonDict:
    runtime = comparisons.get("tsp_controller_vs_tsp_runtime", {})
    applied = _find_runtime_value(runtime, "applied_events", "tsp_controller")
    if applied is not None and applied <= 0:
        return {
            "status": "does_not_demonstrate_actuation",
            "reason": "The controller scenario produced no applied TSP actuation events.",
        }

    controller_kpis = comparisons.get("tsp_controller_vs_sumo_baseline_kpis", {})
    if not controller_kpis.get("available"):
        return {
            "status": "inconclusive_without_sumo_kpis",
            "reason": "Tripinfo/KPI artifacts are required to quantify public transport benefit and general traffic cost.",
        }

    bus_loss_delta = _find_kpi_delta(controller_kpis, "buses", "mean_time_loss_s")
    traffic_loss_delta = _find_kpi_delta(controller_kpis, "general_traffic", "mean_time_loss_s")
    if bus_loss_delta is None:
        return {
            "status": "inconclusive_missing_bus_kpi",
            "reason": "The report could not find bus mean_time_loss_s in the SUMO KPIs.",
        }
    if bus_loss_delta < 0 and (traffic_loss_delta is None or traffic_loss_delta <= 0):
        return {
            "status": "passes_primary_demonstrator_goal",
            "reason": "Bus time loss improved without increasing general traffic mean time loss.",
        }
    if bus_loss_delta < 0:
        return {
            "status": "passes_with_general_traffic_cost",
            "reason": "Bus time loss improved, but general traffic cost increased and must be assessed against policy thresholds.",
        }
    return {
        "status": "does_not_show_public_transport_benefit",
        "reason": "The SUMO KPIs do not show reduced bus mean time loss for the controller scenario.",
    }


def _limitations(*runs: DemonstratorRun) -> List[str]:
    limitations: List[str] = []
    if any(run.kpis is None for run in runs):
        limitations.append("At least one run has no parsed SUMO tripinfo/KPI artifact.")
    if not any(_controller_rejections(run.actuations) for run in runs):
        limitations.append("No controller rejection was observed in the provided runs; rejection paths are covered by unit tests/configuration but not by this evidence run.")
    if not any(d.get("status") == "blocked_by_safety" for run in runs for d in run.decisions):
        limitations.append("No Safety Layer block was observed in the provided runs; safety paths may require stress scenarios to appear in runtime evidence.")
    return limitations


def _load_kpis(root: Path, label: str) -> Optional[JsonDict]:
    candidates = [
        root / f"reports/{label}_kpis.json",
        root / "reports/sumo_kpis.json",
        root / "reports/baseline_kpis.json",
    ]
    for path in candidates:
        payload = _read_json(path)
        if payload is not None:
            return payload
    tripinfo = root / "outputs/tripinfo.xml"
    if tripinfo.exists():
        return parse_tripinfo(tripinfo)
    return None


def _read_json(path: Path) -> Optional[JsonDict]:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _read_jsonl(path: Path) -> List[JsonDict]:
    if not path.exists():
        return []
    rows: List[JsonDict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def _count_by(rows: Iterable[JsonDict], key: str) -> Dict[str, int]:
    return dict(Counter(str(row.get(key, "")) for row in rows if row.get(key) not in {None, ""}))


def _summary_or_count(summary: JsonDict, key: str, fallback_rows: List[JsonDict]) -> int:
    value = summary.get(key)
    return int(value) if isinstance(value, int) else len(fallback_rows)


def _controller_rejections(actuations: Iterable[JsonDict]) -> List[JsonDict]:
    rejected = []
    for item in actuations:
        response = item.get("controller_response")
        if isinstance(response, dict) and response.get("accepted") is False:
            rejected.append(item)
    return rejected


def _controller_rejection_reason(item: JsonDict) -> str:
    response = item.get("controller_response")
    if isinstance(response, dict):
        reason = response.get("reason")
        if reason:
            return str(reason)
    return str(item.get("reason", "unknown"))


def _per_tls(decisions: List[JsonDict], actuations: List[JsonDict], controller_rejections: List[JsonDict]) -> Dict[str, JsonDict]:
    tls_ids = {
        str(item.get("tls_id"))
        for item in [*decisions, *actuations, *controller_rejections]
        if item.get("tls_id")
    }
    payload: Dict[str, JsonDict] = {}
    for tls_id in sorted(tls_ids):
        payload[tls_id] = {
            "decisions": sum(1 for item in decisions if item.get("tls_id") == tls_id),
            "applied_events": sum(1 for item in actuations if item.get("tls_id") == tls_id and item.get("applied")),
            "safety_blocks": sum(
                1 for item in decisions if item.get("tls_id") == tls_id and item.get("status") == "blocked_by_safety"
            ),
            "controller_rejections": sum(1 for item in controller_rejections if item.get("tls_id") == tls_id),
        }
    return payload


def _green_time(decisions: List[JsonDict]) -> JsonDict:
    """Green seconds actually granted to the network.

    Sums `extension_s` over APPROVED decisions only (those that passed the
    Safety Layer and were applied), so this is the dose delivered — not merely
    decided. Grounded entirely in the persisted decision log; nothing inferred.
    """
    approved = [d for d in decisions if d.get("status") == "approved"]
    ext = [float(d.get("extension_s") or 0.0) for d in approved]
    granting = [e for e in ext if e > 0]
    return {
        "applied_extension_s_total": round(sum(ext), 1),
        "mean_extension_s": round(sum(granting) / len(granting), 1) if granting else 0.0,
        "max_extension_s": round(max(ext), 1) if ext else 0.0,
        "n_extensions": len(granting),
    }


def _score_attribution(decisions: List[JsonDict]) -> Dict[str, float]:
    """Mean per-objective contribution across actuating (approved) decisions —
    which objective (delay, headway, proximity, priority level) drove the
    priority score that led to actuation. Reads `score_components.contribution`
    already computed by the engine; nothing is recomputed here."""
    actuating = [
        d for d in decisions
        if d.get("status") == "approved" and isinstance(d.get("score_components"), dict)
    ]
    if not actuating:
        return {}
    totals: Dict[str, float] = {}
    for d in actuating:
        for objective, comp in d["score_components"].items():
            contribution = comp.get("contribution") if isinstance(comp, dict) else None
            if isinstance(contribution, (int, float)):
                totals[objective] = totals.get(objective, 0.0) + float(contribution)
    return {objective: round(value / len(actuating), 4) for objective, value in totals.items()}


def _evidence_paths(run: DemonstratorRun) -> JsonDict:
    return {
        "root": str(run.root),
        "decisions": str(run.root / "outputs/tsp_decisions.jsonl"),
        "actuations": str(run.root / "outputs/tsp_actuation.jsonl"),
        "tripinfo": str(run.root / "outputs/tripinfo.xml"),
        "tsp_summary": str(run.root / "reports/tsp_emulation_summary.json"),
        "cits_summary": str(run.root / "reports/cits_emulation_summary.json"),
    }


def _find_kpi_delta(comparison: JsonDict, group: str, metric: str) -> Optional[float]:
    for row in comparison.get("rows", []):
        if row.get("group") == group and row.get("metric") == metric:
            delta = row.get("delta")
            return float(delta) if isinstance(delta, (int, float)) else None
    return None


def _find_runtime_value(comparison: JsonDict, metric: str, column: str) -> Optional[float]:
    for row in comparison.get("rows", []):
        if row.get("metric") == metric:
            value = row.get(column)
            return float(value) if isinstance(value, (int, float)) else None
    return None


def _delta(left: Any, right: Any) -> Optional[float]:
    if isinstance(left, bool) or isinstance(right, bool):
        return None
    if isinstance(left, (int, float)) and isinstance(right, (int, float)):
        return round(float(right) - float(left), 4)
    return None


def _counter_section(title: str, values: JsonDict) -> List[str]:
    lines = [f"### {title}", ""]
    if not values:
        return [*lines, "None observed.", ""]
    lines.extend(["| Reason | Count |", "|---|---:|"])
    for reason, count in sorted(values.items()):
        lines.append(f"| {_escape(str(reason))} | {count} |")
    lines.append("")
    return lines


def _fmt(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".")
    return _escape(str(value))


def _escape(value: str) -> str:
    return value.replace("|", "\\|")
